"""create_initial_tables

Revision ID: 3f5f159e3b50
Revises: 
Create Date: 2026-09-22 00:40:42.850952

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f5f159e3b50'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cloud_accounts',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.Enum('AWS', 'AZURE', 'GCP', 'MULTI', name='cloudprovider'), nullable=False),
    sa.Column('account_id', sa.String(length=255), nullable=False),
    sa.Column('environment', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('credentials_encrypted', sa.Text(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_simulated', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compliance_frameworks',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('total_controls', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gemini_audit_logs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('category', sa.Enum('FINDING_ANALYSIS', 'INCIDENT_ROOT_CAUSE', 'REMEDIATION_GEN', 'EXECUTIVE_SUMMARY', 'BLAST_RADIUS', 'THREAT_MODEL', name='promptcategoryenum'), nullable=False),
    sa.Column('model_name', sa.String(length=64), nullable=False),
    sa.Column('target_entity_type', sa.String(length=64), nullable=False),
    sa.Column('target_entity_id', sa.String(length=64), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('user_prompt', sa.Text(), nullable=False),
    sa.Column('raw_response', sa.Text(), nullable=False),
    sa.Column('parsed_json', sa.JSON(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('is_fallback', sa.Boolean(), nullable=False),
    sa.Column('fallback_reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_simulated', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gemini_audit_logs_category'), 'gemini_audit_logs', ['category'], unique=False)
    op.create_index(op.f('ix_gemini_audit_logs_target_entity_id'), 'gemini_audit_logs', ['target_entity_id'], unique=False)
    op.create_table('security_rules',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('IAM', 'STORAGE', 'NETWORK', 'COMPUTE', 'DATABASE', 'ENCRYPTION', 'LOGGING', 'COMPLIANCE', name='rulecategoryenum'), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('default_severity', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'INFORMATIONAL', name='severityenum'), nullable=False),
    sa.Column('remediation_template', sa.Text(), nullable=True),
    sa.Column('framework_mappings', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_rules_category'), 'security_rules', ['category'], unique=False)
    op.create_index(op.f('ix_security_rules_provider'), 'security_rules', ['provider'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'SECURITY_ANALYST', 'VIEWER', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('sequence_number', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('actor_id', sa.String(length=64), nullable=True),
    sa.Column('actor_email', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('action', sa.Enum('USER_LOGIN', 'USER_LOGOUT', 'USER_REGISTER', 'INGESTION_TRIGGERED', 'INGESTION_COMPLETED', 'SCAN_TRIGGERED', 'SCAN_COMPLETED', 'RULE_CREATED', 'RULE_UPDATED', 'FINDING_STATUS_CHANGE', 'INCIDENT_CREATED', 'INCIDENT_STATUS_CHANGE', 'REMEDIATION_PROPOSED', 'REMEDIATION_APPROVED', 'REMEDIATION_EXECUTED', 'SYSTEM_CONFIG_CHANGE', name='auditactionenum'), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('previous_hash', sa.String(length=64), nullable=False),
    sa.Column('current_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('current_hash')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_sequence_number'), 'audit_logs', ['sequence_number'], unique=True)
    op.create_table('compliance_assessments',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('cloud_account_id', sa.String(length=64), nullable=False),
    sa.Column('framework_id', sa.String(length=64), nullable=False),
    sa.Column('score_percent', sa.Float(), nullable=False),
    sa.Column('passed_controls', sa.Integer(), nullable=False),
    sa.Column('failed_controls', sa.Integer(), nullable=False),
    sa.Column('total_evaluated', sa.Integer(), nullable=False),
    sa.Column('detailed_results', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cloud_account_id'], ['cloud_accounts.id'], ),
    sa.ForeignKeyConstraint(['framework_id'], ['compliance_frameworks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_assessments_cloud_account_id'), 'compliance_assessments', ['cloud_account_id'], unique=False)
    op.create_index(op.f('ix_compliance_assessments_framework_id'), 'compliance_assessments', ['framework_id'], unique=False)
    op.create_table('compliance_controls',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('framework_id', sa.String(length=64), nullable=False),
    sa.Column('control_code', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('domain', sa.String(length=128), nullable=False),
    sa.Column('mapped_rule_ids', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['framework_id'], ['compliance_frameworks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_controls_framework_id'), 'compliance_controls', ['framework_id'], unique=False)
    op.create_table('data_sources',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.Enum('LIVE_AWS', 'LIVE_AZURE', 'LIVE_GCP', 'USER_UPLOAD', 'API_INGESTION', 'USER_GENERATED_TEST', 'DEMO', name='sourcetype'), nullable=False),
    sa.Column('cloud_account_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('last_ingested_at', sa.DateTime(), nullable=True),
    sa.Column('total_records_ingested', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_simulated', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['cloud_account_id'], ['cloud_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('incidents',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('cloud_account_id', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.Enum('P1_CRITICAL', 'P2_HIGH', 'P3_MEDIUM', 'P4_LOW', name='incidentseverityenum'), nullable=False),
    sa.Column('status', sa.Enum('DETECTED', 'TRIAGED', 'INVESTIGATING', 'CONTAINED', 'REMEDIATED', 'CLOSED', name='incidentstatusenum'), nullable=False),
    sa.Column('assigned_to', sa.String(length=64), nullable=True),
    sa.Column('mitre_attack_tactics', sa.JSON(), nullable=True),
    sa.Column('mitre_attack_techniques', sa.JSON(), nullable=True),
    sa.Column('blast_radius_summary', sa.Text(), nullable=True),
    sa.Column('ai_root_cause_analysis', sa.Text(), nullable=True),
    sa.Column('ai_containment_plan', sa.Text(), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.Column('contained_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('related_finding_ids', sa.JSON(), nullable=True),
    sa.Column('related_resource_ids', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_simulated', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['cloud_account_id'], ['cloud_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidents_cloud_account_id'), 'incidents', ['cloud_account_id'], unique=False)
    op.create_index(op.f('ix_incidents_severity'), 'incidents', ['severity'], unique=False)
    op.create_index(op.f('ix_incidents_status'), 'incidents', ['status'], unique=False)
    op.create_table('telemetry_logs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('cloud_account_id', sa.String(length=64), nullable=False),
    sa.Column('source_type', sa.Enum('AWS_CLOUDTRAIL', 'AWS_VPC_FLOW', 'AWS_GUARDDUTY', 'AZURE_ACTIVITY', 'GCP_AUDIT', 'KUBERNETES_AUDIT', name='logsourcetype'), nullable=False),
    sa.Column('event_timestamp', sa.DateTime(), nullable=False),
    sa.Column('event_name', sa.String(length=128), nullable=False),
    sa.Column('actor_identity', sa.String(length=255), nullable=True),
    sa.Column('source_ip', sa.String(length=64), nullable=True),
    sa.Column('source_geo', sa.String(length=64), nullable=True),
    sa.Column('target_resource_id', sa.String(length=255), nullable=True),
    sa.Column('status_code', sa.String(length=32), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('is_anomalous', sa.Boolean(), nullable=False),
    sa.Column('anomaly_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_simulated', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['cloud_account_id'], ['cloud_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telemetry_logs_cloud_account_id'), 'telemetry_logs', ['cloud_account_id'], unique=False)
    op.create_index(op.f('ix_telemetry_logs_event_name'), 'telemetry_logs', ['event_name'], unique=False)
    op.create_index(op.f('ix_telemetry_logs_event_timestamp'), 'telemetry_logs', ['event_timestamp'], unique=False)
    op.create_index(op.f('ix_telemetry_logs_is_anomalous'), 'telemetry_logs', ['is_anomalous'], unique=False)
    op.create_index(op.f('ix_telemetry_logs_source_ip'), 'telemetry_logs', ['source_ip'], unique=False)
    op.create_index(op.f('ix_telemetry_logs_source_type'), 'telemetry_logs', ['source_type'], unique=False)
    op.create_table('anomaly_events',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('cloud_account_id', sa.String(length=64), nullable=False),
    sa.Column('detector_name', sa.String(length=64), nullable=False),
    sa.Column('feature_vector', sa.JSON(), nullable=False),
    sa.Column('anomaly_score', sa.Float(), nullable=False),
    sa.Column('baseline_deviation_percent', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('top_contributing_features', sa.JSON(), nullable=False),
    sa.Column('incident_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_simulated', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['cloud_account_id'], ['cloud_accounts.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anomaly_events_cloud_account_id'), 'anomaly_events', ['cloud_account_id'], unique=False)
    op.create_index(op.f('ix_anomaly_events_incident_id'), 'anomaly_events', ['incident_id'], unique=False)
    op.create_table('cloud_resources',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('cloud_account_id', sa.String(length=64), nullable=True),
    sa.Column('native_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=False),
    sa.Column('configuration', sa.JSON(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('data_source_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_simulated', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['cloud_account_id'], ['cloud_accounts.id'], ),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_resource_cloud_account', 'cloud_resources', ['cloud_account_id'], unique=False)
    op.create_index('ix_resource_provider', 'cloud_resources', ['provider'], unique=False)
    op.create_table('incident_timelines',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('incident_id', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('author_id', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_timelines_incident_id'), 'incident_timelines', ['incident_id'], unique=False)
    op.create_table('ingestion_jobs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('data_source_id', sa.String(length=64), nullable=False),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='jobstatus'), nullable=False),
    sa.Column('records_processed', sa.Integer(), nullable=False),
    sa.Column('records_failed', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('findings',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('rule_id', sa.String(length=64), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=False),
    sa.Column('cloud_account_id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'INFORMATIONAL', name='severityenum'), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'REMEDIATED', 'RESOLVED', 'DISMISSED', 'SUPPRESSED', name='findingstatusenum'), nullable=False),
    sa.Column('evidence_summary', sa.Text(), nullable=True),
    sa.Column('raw_evidence', sa.JSON(), nullable=True),
    sa.Column('remediation_guidance', sa.Text(), nullable=True),
    sa.Column('risk_score_contribution', sa.Float(), nullable=False),
    sa.Column('ai_analyzed', sa.Boolean(), nullable=False),
    sa.Column('ai_risk_assessment', sa.Text(), nullable=True),
    sa.Column('compliance_controls', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_simulated', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['cloud_account_id'], ['cloud_accounts.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['cloud_resources.id'], ),
    sa.ForeignKeyConstraint(['rule_id'], ['security_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_finding_account_severity', 'findings', ['cloud_account_id', 'severity'], unique=False)
    op.create_index('ix_finding_account_status', 'findings', ['cloud_account_id', 'status'], unique=False)
    op.create_index(op.f('ix_findings_cloud_account_id'), 'findings', ['cloud_account_id'], unique=False)
    op.create_index(op.f('ix_findings_resource_id'), 'findings', ['resource_id'], unique=False)
    op.create_index(op.f('ix_findings_rule_id'), 'findings', ['rule_id'], unique=False)
    op.create_index(op.f('ix_findings_severity'), 'findings', ['severity'], unique=False)
    op.create_index(op.f('ix_findings_status'), 'findings', ['status'], unique=False)
    op.create_table('resource_snapshots',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=False),
    sa.Column('configuration', sa.JSON(), nullable=False),
    sa.Column('snapshot_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['cloud_resources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('finding_evidences',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('finding_id', sa.String(length=64), nullable=False),
    sa.Column('evidence_type', sa.String(length=64), nullable=False),
    sa.Column('source_component', sa.String(length=128), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('hash_sha256', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finding_evidences_finding_id'), 'finding_evidences', ['finding_id'], unique=False)
    op.create_table('remediation_plans',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('finding_id', sa.String(length=64), nullable=True),
    sa.Column('incident_id', sa.String(length=64), nullable=True),
    sa.Column('cloud_account_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('PROPOSED', 'DRY_RUN_COMPLETED', 'APPROVED', 'EXECUTING', 'COMPLETED', 'FAILED', 'ROLLED_BACK', name='remediationplanstatus'), nullable=False),
    sa.Column('risk_tier', sa.Enum('SAFE_AUTO', 'HUMAN_CONFIRM', 'ELEVATED', name='actionrisktier'), nullable=False),
    sa.Column('cli_commands', sa.JSON(), nullable=True),
    sa.Column('terraform_hcl', sa.Text(), nullable=True),
    sa.Column('python_script', sa.Text(), nullable=True),
    sa.Column('dry_run_output', sa.JSON(), nullable=True),
    sa.Column('dry_run_success', sa.Boolean(), nullable=True),
    sa.Column('approved_by', sa.String(length=64), nullable=True),
    sa.Column('executed_by', sa.String(length=64), nullable=True),
    sa.Column('execution_result', sa.JSON(), nullable=True),
    sa.Column('post_verification_status', sa.String(length=64), nullable=True),
    sa.Column('rollback_script', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_simulated', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['cloud_account_id'], ['cloud_accounts.id'], ),
    sa.ForeignKeyConstraint(['executed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['finding_id'], ['findings.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_remediation_plans_cloud_account_id'), 'remediation_plans', ['cloud_account_id'], unique=False)
    op.create_index(op.f('ix_remediation_plans_finding_id'), 'remediation_plans', ['finding_id'], unique=False)
    op.create_index(op.f('ix_remediation_plans_incident_id'), 'remediation_plans', ['incident_id'], unique=False)
    op.create_index(op.f('ix_remediation_plans_status'), 'remediation_plans', ['status'], unique=False)
    op.create_table('verification_scans',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('remediation_plan_id', sa.String(length=64), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=False),
    sa.Column('rule_id', sa.String(length=64), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('raw_scan_output', sa.JSON(), nullable=False),
    sa.Column('execution_time_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['remediation_plan_id'], ['remediation_plans.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['cloud_resources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_scans_remediation_plan_id'), 'verification_scans', ['remediation_plan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verification_scans_remediation_plan_id'), table_name='verification_scans')
    op.drop_table('verification_scans')
    op.drop_index(op.f('ix_remediation_plans_status'), table_name='remediation_plans')
    op.drop_index(op.f('ix_remediation_plans_incident_id'), table_name='remediation_plans')
    op.drop_index(op.f('ix_remediation_plans_finding_id'), table_name='remediation_plans')
    op.drop_index(op.f('ix_remediation_plans_cloud_account_id'), table_name='remediation_plans')
    op.drop_table('remediation_plans')
    op.drop_index(op.f('ix_finding_evidences_finding_id'), table_name='finding_evidences')
    op.drop_table('finding_evidences')
    op.drop_table('resource_snapshots')
    op.drop_index(op.f('ix_findings_status'), table_name='findings')
    op.drop_index(op.f('ix_findings_severity'), table_name='findings')
    op.drop_index(op.f('ix_findings_rule_id'), table_name='findings')
    op.drop_index(op.f('ix_findings_resource_id'), table_name='findings')
    op.drop_index(op.f('ix_findings_cloud_account_id'), table_name='findings')
    op.drop_index('ix_finding_account_status', table_name='findings')
    op.drop_index('ix_finding_account_severity', table_name='findings')
    op.drop_table('findings')
    op.drop_table('ingestion_jobs')
    op.drop_index(op.f('ix_incident_timelines_incident_id'), table_name='incident_timelines')
    op.drop_table('incident_timelines')
    op.drop_index('ix_resource_provider', table_name='cloud_resources')
    op.drop_index('ix_resource_cloud_account', table_name='cloud_resources')
    op.drop_table('cloud_resources')
    op.drop_index(op.f('ix_anomaly_events_incident_id'), table_name='anomaly_events')
    op.drop_index(op.f('ix_anomaly_events_cloud_account_id'), table_name='anomaly_events')
    op.drop_table('anomaly_events')
    op.drop_index(op.f('ix_telemetry_logs_source_type'), table_name='telemetry_logs')
    op.drop_index(op.f('ix_telemetry_logs_source_ip'), table_name='telemetry_logs')
    op.drop_index(op.f('ix_telemetry_logs_is_anomalous'), table_name='telemetry_logs')
    op.drop_index(op.f('ix_telemetry_logs_event_timestamp'), table_name='telemetry_logs')
    op.drop_index(op.f('ix_telemetry_logs_event_name'), table_name='telemetry_logs')
    op.drop_index(op.f('ix_telemetry_logs_cloud_account_id'), table_name='telemetry_logs')
    op.drop_table('telemetry_logs')
    op.drop_index(op.f('ix_incidents_status'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_severity'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_cloud_account_id'), table_name='incidents')
    op.drop_table('incidents')
    op.drop_table('data_sources')
    op.drop_index(op.f('ix_compliance_controls_framework_id'), table_name='compliance_controls')
    op.drop_table('compliance_controls')
    op.drop_index(op.f('ix_compliance_assessments_framework_id'), table_name='compliance_assessments')
    op.drop_index(op.f('ix_compliance_assessments_cloud_account_id'), table_name='compliance_assessments')
    op.drop_table('compliance_assessments')
    op.drop_index(op.f('ix_audit_logs_sequence_number'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_security_rules_provider'), table_name='security_rules')
    op.drop_index(op.f('ix_security_rules_category'), table_name='security_rules')
    op.drop_table('security_rules')
    op.drop_index(op.f('ix_gemini_audit_logs_target_entity_id'), table_name='gemini_audit_logs')
    op.drop_index(op.f('ix_gemini_audit_logs_category'), table_name='gemini_audit_logs')
    op.drop_table('gemini_audit_logs')
    op.drop_table('compliance_frameworks')
    op.drop_table('cloud_accounts')
    # ### end Alembic commands ###
